### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by dinever** [dinever/dingo#18]
I'm thinking about creating an organization for this project. Then we can move this repo into the org, and add our contributors as organization members.

However, we need a logo for the avatar of the future organization. Otherwise, Dingo will lose its coolness with the default avatar from GitHub.

**Comment by dinever** [comment]
Done.

![artboard 1](https://cloud.githubusercontent.com/assets/1311594/15342855/79c69a10-1c66-11e6-85e3-71c5bb6aee89.png)

**Comment by dinever** [comment]
@nak3 @bentranter @samdfonseca 

Hi guys,

Just have invited you into the organization I created, will transfer this repo into the org later.

**Comment by bentranter** [comment]
This looks awesome!

**Comment by nak3** [comment]
Sure! Thank you @dinever and nice log!

**Comment by samdfonseca** [comment]
very cool. reminds me of the beats headphones logo.
