### ISSUE TITLE
New Post can't be saved

### ISSUE THREAD

**Issue by nak3** [dinever/dingo#19]
From Web UI,

`Posts`->`+(Add)`->`SAVE` doesn't work. No answer from browser, although console outputs the access `The 2016/04/29 - 19:49:24 | 400 |     627.657µs | ::1 |   POST    /admin/editor/post/`.  I tested Firefox 44.0 and Chrome 48.0.2564.103.

As far as I tested, the issue happened between these commits:

commit [48d6cca055bfea7729329c6dea5b7448fc71c5f2](https://github.com/dinever/dingo/commit/48d6cca055bfea7729329c6dea5b7448fc71c5f2) worked well.
commit [33dc9a5a40121edba8d8a2d60d61a58fe4a79747](https://github.com/dinever/dingo/commit/33dc9a5a40121edba8d8a2d60d61a58fe4a79747) doesn't work.

**Comment by dinever** [comment]
Thanks. Will take a look at this.

**Comment by dinever** [comment]
Seems that this is because the user didn't input anything in the slug field, the server responded with an error message but the JS didn't pop up an error notification.

Will fix this in the new admin UI.

**Comment by nak3** [comment]
@dinever I think we can close this issue, thanks to the new amin UI.

**Comment by dinever** [comment]
Thanks @nak3!
