### ISSUE TITLE
Non-exisiting page accesses are not handled correctly

### ISSUE THREAD

**Issue by nak3** [dinever/dingo#30]
Please check following reproduce steps:

step1. Start dingo

~~~
$ go run main.go
Database is used at dingo.db
Application Started on port 8000
~~~

step2. Access to invalid page (before login)

e.g. [http://localhost:8000/foo](http://localhost:8000/foo)

This steps produces 500 Internal error with go panic.

**Comment by dinever** [comment]
Thanks. I'm going to fix this and add some test cases.
