### ISSUE TITLE
A better way to create Dingo application in test cases.

### ISSUE THREAD

**Issue by dinever** [dinever/dingo#35]
As we need to create a Dingo app mock-up for testing handlers, we need to register all of the routes in [app/app.go](https://github.com/dinever/dingo/blob/master/app/app.go) for the app mock-up. However, we can not import `github.com/dinever/dingo/app` in handlers because of cyclic imports. 

The temporary solution is to create a copy of those routes in [app/handler/urls.go](https://github.com/dinever/dingo/blob/master/app/app.go), which is pretty clumsy. We need to come up with a way to handle this gracefully.

**Comment by nak3** [comment]
@dinever You don't want to move golf app interface to handler package? If not, we can solve the issue like this https://github.com/dinever/dingo/pull/37

**Comment by dinever** [comment]
Closed in favor of #37
