### ISSUE TITLE
Latest published post should be top

### ISSUE THREAD

**Issue by nak3** [dinever/dingo#47]
Current published blog posts are descending order by created date(time). Welcome Post (`Welcome to Dingo!`) always comes to the Top post.

**Comment by dinever** [comment]
Hi @nak3,

Sorry for the late response to this, I am a little bit busy with my final exams during these two weeks. 😸 

Seems that we can not use placeholder `?` to specify the `ORDER BY` values. Maybe we should insert it using `fmt.Sprintf`.

Reference: [stackoverflow.com/a/30867686/1983467](http://stackoverflow.com/a/30867686/1983467)

**Comment by nak3** [comment]
@dinever Thank you! I'm sorry It was my mistake X(
Thank you for your fix!
